### ISSUE TITLE
src for script tags is not in the zip

### ISSUE THREAD

**Issue by riderfan** [ArrobeFr/jquery-calendar-bs4#1]
I downloaded the zip file and all of the src's in the script tags at the top of the example.html file are not included.   More specifically, the node_modules folder isn't there.  The plug-in doesn't function without them

**Comment by PingHarsha** [comment]
`  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/moment@2.22.1/min/moment-with-locales.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/jquery-touchswipe@1.6.18/jquery.touchSwipe.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/eonasdan-bootstrap-datetimepicker@4.17.47/build/js/bootstrap-datetimepicker.min.js"></script>
  <script src="../dist/js/jquery-calendar.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/arrobefr-jquery-calendar@1.0.10/dist/css/jquery-calendar.min.css">
  <script src="https://cdn.jsdelivr.net/npm/pouchdb@6.4.3/dist/pouchdb.min.js"></script>`

**Comment by LeoVillaretArrobe** [comment]
Thanks to @PingHarsha, his response is true.

The `node_modules` is not included but the dependencies are in a `package.json` file.

So, using the zip file, you can just run a `npm install` to install dependencies in the `node_modules` directory.

You can also just use `npm`, please read the `README.md`
