### ISSUE TITLE
Calendar not working as documented or expected

### ISSUE THREAD

**Issue by webcliq** [ArrobeFr/jquery-calendar-bs4#2]
[test_cliqi_net.zip](https://github.com/ArrobeFr/jquery-calendar-bs4/files/2282773/test_cliqi_net.zip)

In order to demonstrate the problem, I created a simple test site on my development machine and I attach a ZIP archive of that website.

I would like to separate the loading of the Calendar from the events so that I can load, update and delete events via Ajax.

To achieve this I tried to follow your documentation and use "calendar.setEvents()" as a separate action. When it did not work I back tracked until I created the simple use case attached.

      /**
       * Init the calendar
       */
      var calendar = $('#calendar').Calendar({
        locale: 'en',
        weekday: {
          timeline: {
            intervalMinutes: 30,
            fromHour: 9
          }
        }
      }).init();
      var events = calendar.setEvents(events).init();

The JS Console reports for the second line that "calendar" is not defined. Or to put it another way, your code is not returning anything on the first line that the Object named calendar can store.

**Comment by PingHarsha** [comment]
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/moment@2.22.1/min/moment-with-locales.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/jquery-touchswipe@1.6.18/jquery.touchSwipe.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/eonasdan-bootstrap-datetimepicker@4.17.47/build/js/bootstrap-datetimepicker.min.js"></script>
  <script src="../dist/js/jquery-calendar.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/arrobefr-jquery-calendar@1.0.10/dist/css/jquery-calendar.min.css">
  <script src="https://cdn.jsdelivr.net/npm/pouchdb@6.4.3/dist/pouchdb.min.js"></script>
use these CDNs

**Comment by myseocompany** [comment]
I think that you must first create the object in order to use it lately. Try this:

```javascript
/**
   * Init the calendar
   */
  var calendar = $('#calendar').Calendar({
    locale: 'en',
    weekday: {
      timeline: {
        intervalMinutes: 30,
        fromHour: 9
      }
    }
  });
  calendar.init();
  var events = calendar.setEvents(events);

**Comment by LeoVillaretArrobe** [comment]
Thanks agin to @myseocompany 

It is true. I found that the `.init()` does not return the `Calendar` instance.

The code working like that :

```js
var calendar = $('#calendar').Calendar({
        locale: 'en',
        weekday: {
          timeline: {
            intervalMinutes: 30,
            fromHour: 9
          }
        }
      });
      calendar.init();
      var events = calendar.setEvents(events);
      calendar.init();
```

Maybe some methods must returns the object ? @webcliq @PingHarsha @myseocompany 

Adding the returns of object allows to write like that :
```js
var calendar = $('#calendar').Calendar({
        locale: 'en',
        weekday: {
          timeline: {
            intervalMinutes: 30,
            fromHour: 9
          }
        }
      }).init().setEvents(events).init();
```

**Comment by LeoVillaretArrobe** [comment]
The [bootstrap 3 version](https://github.com/ArrobeFr/jquery-calendar) get an upgrade, the new release fix that. I will release for this repository too now.
