### ISSUE TITLE
How to set ID for each Event.

### ISSUE THREAD

**Issue by kumarDev83** [ArrobeFr/jquery-calendar-bs4#3]
This is not really an issue but a question. I need to be able to find out on which event user has clicked but I have no way to specify an Id for the event.

**Comment by LeoVillaretArrobe** [comment]
An avent must have the [following attributes](https://github.com/ArrobeFr/jquery-calendar-bs4#attributes)

But you can extends the object. Example following [this](https://github.com/ArrobeFr/jquery-calendar-bs4/blob/master/example/example.html#L28) :

```js
var events = [
    {
         id: 1,         // Your id
         foo: 'bar',    // Anything else
         start: now.startOf('week').add(9, 'h').format('X'),
         end: now.startOf('week').add(10, 'h').format('X'),
         title: '1',
         content: 'Hello World! <br> <p>Foo Bar</p>',
         category:'Professionnal'
    }
]
```
